<?php

namespace App\DataFixtures\Faker\Provider;

use Faker\Provider\Base;

class CoverProvider extends Base
{
    private const FILES = [
        '/fixtures/files/test.jpg',
        '/fixtures/files/test_1.jpg',
        '/fixtures/files/test_2.jpg',
        '/fixtures/files/test_3.jpg',
    ];

    /**
     * Get random image url for the cloudinary CDN.
     *
     * @return string
     *   A random realistic CDN URL
     */
    public function remoteUrl(): string
    {
        return 'https://res.cloudinary.com/dandigbib/image/upload/v1543609481//FixturesData/'.$this->pid().'.jpg';
    }

    /**
     * Get a random filepath resembling what is generated by the Vich namer.
     *
     * @return string
     */
    public function filePath(): string
    {
        return $this->generator->lexify('?????????????').$this->pid().'.jpeg';
    }

    /**
     * Get a semi-realistic random agency id.
     *
     * @return int
     */
    public function agencyId(): int
    {
        return self::numberBetween(70000, 90000) * 10;
    }

    /**
     * Get the filename for a file in the filesystem. File will be one of the images in fixtures.
     *
     * @param string $env
     *   The kernel environment. Will be used as prefix for the filename.
     *
     * @return string
     *   The filename
     */
    public static function randomImage(string $env = 'dev'): string
    {
        $file = self::getProjectDir().self::FILES[array_rand(self::FILES)];
        $new = self::getProjectDir().'/public/cover/'.$env.'_fixture_'.str_shuffle(sha1((string) time())).'.jpg';
        file_put_contents($new, file_get_contents($file));

        return \basename($new);
    }

    /**
     * Get sha1 hash for a file.
     *
     * @param string $file
     *   The file
     *
     * @return string
     *   The hash
     */
    public static function fileSha(string $file): string
    {
        return \sha1(self::getPublicFile($file));
    }

    /**
     * Get the filesize of a file.
     *
     * @param string $file
     *   The file
     *
     * @return int
     *   The file size
     */
    public static function imageSize(string $file): int
    {
        return \filesize(self::getPublicFile($file));
    }

    /**
     * Get the with of an image.
     *
     * @param string $file
     *   The image file
     *
     * @return int
     *   The with
     */
    public static function imageWidth(string $file): int
    {
        return \getimagesize(self::getPublicFile($file))[0];
    }

    /**
     * Get the height of an image.
     *
     * @param string $file
     *   The image file
     *
     * @return int
     *   The height
     */
    public static function imageHeight(string $file): int
    {
        return \getimagesize(self::getPublicFile($file))[1];
    }

    /**
     * Get the mimetype of an image.
     *
     * @param string $file
     *   The image file
     *
     * @return string
     *   Yhe mimetype
     */
    public static function fileMimeType(string $file): string
    {
        return \getimagesize(self::getPublicFile($file))['mime'];
    }

    /**
     * Get a random pid number.
     *
     * @return string
     *   A random but pseudo realistic pid identifier
     */
    public function pid(): string
    {
        $libraryNumber = self::numberBetween(70000, 90000) * 10;

        return $libraryNumber.'-basis:'.self::randomNumber(8);
    }

    /**
     * Get the project dir.
     *
     * @return string
     */
    private static function getProjectDir(): string
    {
        return !empty($GLOBALS['app']) ? $GLOBALS['app']->getKernel()->getProjectDir() : getcwd();
    }

    /**
     * Get the public file path for a file.
     *
     * @param string $file
     *   The file
     *
     * @return string
     *   Filepath
     */
    private static function getPublicFile(string $file): string
    {
        return self::getProjectDir().'/public/cover/'.$file;
    }

    /**
     * Cleanup all files for the kernel environment.
     *
     * @param string $env
     *   The kernel environment,
     *
     * @return void
     */
    public static function cleanupFiles(string $env = 'dev'): void
    {
        $files = \scandir(self::getProjectDir().'/public/cover/');

        foreach ($files as $file) {
            $filename = self::getProjectDir().'/public/cover/'.$file;
            if (\str_starts_with($file, $env.'_fixture_') && \is_file($filename)) {
                \unlink($filename);
            }
        }
    }
}
